source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "minimal-mistakes-jekyll"
gem "jekyll-feed", "~> 0.12"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-seo-tag", "~> 2.8"

# GitHub Pages用のプラグイン（後で有効化する場合はコメントを外す）
# group :github_pages do
#   gem "github-pages", group: :jekyll_plugins
# end

